# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-02-19 09:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='addressing_date',
            field=models.DateField(blank=True, default=datetime.date(2017, 2, 19)),
        ),
        migrations.AddField(
            model_name='complaint',
            name='lodge_date',
            field=models.DateField(blank=True, default=datetime.date(2017, 2, 19)),
        ),
    ]
