# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-04-21 17:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complainee',
            name='mobile_no',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='complainee',
            name='room_no',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='addressing_date',
            field=models.DateField(blank=True, default=datetime.date(2017, 4, 22)),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='lodge_date',
            field=models.DateField(blank=True, default=datetime.date(2017, 4, 21)),
        ),
    ]
