# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-04-21 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20170421_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complainee',
            name='mobile_no',
            field=models.PositiveIntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='complainee',
            name='room_no',
            field=models.PositiveIntegerField(max_length=4),
        ),
    ]
