# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-02-19 16:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20170219_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complainee',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='complainee', to=settings.AUTH_USER_MODEL),
        ),
    ]
