# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-04-21 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20170421_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='feedback',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='subject',
            field=models.CharField(max_length=150),
        ),
    ]
